/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectosuperautos;
 
import Clases.Conexionsqlnetbeans;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.security.Principal;
import java.sql.Connection;
import java.sql.PreparedStatement; 
import java.sql.ResultSet;
import java.sql.SQLException; 
import javax.swing.JOptionPane;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JPanel;
/**
 *
 * @author Sthefany
 */
public class Menu extends javax.swing.JFrame {
Conexionsqlnetbeans cone = new Conexionsqlnetbeans();
int xMouse;
int yMouse;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null); 
         
         rsscalelabel.RSScaleLabel.setScaleLabel(ProgramaAutos, "src/RecursosImagenes/Logo150.png");
           
         PrincipalMenu p1 = new PrincipalMenu () {};
       ShowPanel((JPanel) p1.getContentPane());    
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Background = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        BtnPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BtnVehiculos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnVentas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BtnProveedores = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BtnEmpleados = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BtnClientes = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ProgramaAutos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BtnPlanilla = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        BtnCatalogo = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        BtnSucursales = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        BtnUsuarios = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        BtnCerrarSesion = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        BtnTransacciones = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        BtnCatalogo1 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        BtnCatalogo2 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        BtnCatalogo3 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        BtnEmpleados1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        Title = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        red_squr = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        Mnimizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(156, 210, 176));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnPrincipal.setBackground(new java.awt.Color(73, 176, 111));
        BtnPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        BtnPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPrincipalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnPrincipalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnPrincipalMousePressed(evt);
            }
        });
        BtnPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosImagenes/PrincipalIcon.png"))); // NOI18N
        BtnPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Principal");
        BtnPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(BtnPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 270, 50));

        BtnVehiculos.setBackground(new java.awt.Color(73, 176, 111));
        BtnVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        BtnVehiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnVehiculos.setPreferredSize(new java.awt.Dimension(270, 51));
        BtnVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnVehiculosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnVehiculosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnVehiculosMousePressed(evt);
            }
        });
        BtnVehiculos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosImagenes/VehiculoIcon.png"))); // NOI18N
        BtnVehiculos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vehículos");
        BtnVehiculos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(BtnVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        BtnVentas.setBackground(new java.awt.Color(73, 176, 111));
        BtnVentas.setForeground(new java.awt.Color(255, 255, 255));
        BtnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnVentas.setPreferredSize(new java.awt.Dimension(270, 51));
        BtnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnVentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnVentasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnVentasMousePressed(evt);
            }
        });
        BtnVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosImagenes/Sale.png"))); // NOI18N
        BtnVentas.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ventas");
        BtnVentas.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(BtnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        BtnProveedores.setBackground(new java.awt.Color(73, 176, 111));
        BtnProveedores.setForeground(new java.awt.Color(255, 255, 255));
        BtnProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnProveedores.setPreferredSize(new java.awt.Dimension(270, 51));
        BtnProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnProveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnProveedoresMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnProveedoresMousePressed(evt);
            }
        });
        BtnProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosImagenes/provider.png"))); // NOI18N
        BtnProveedores.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Proveedores");
        BtnProveedores.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(BtnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        BtnEmpleados.setBackground(new java.awt.Color(73, 176, 111));
        BtnEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        BtnEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnEmpleados.setPreferredSize(new java.awt.Dimension(270, 51));
        BtnEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEmpleadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEmpleadosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnEmpleadosMousePressed(evt);
            }
        });
        BtnEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosImagenes/employees.png"))); // NOI18N
        BtnEmpleados.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Empleados");
        BtnEmpleados.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 30));

        Menu.add(BtnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 441, -1, 30));

        BtnClientes.setBackground(new java.awt.Color(73, 176, 111));
        BtnClientes.setForeground(new java.awt.Color(255, 255, 255));
        BtnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnClientes.setPreferredSize(new java.awt.Dimension(270, 51));
        BtnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnClientesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnClientesMousePressed(evt);
            }
        });
        BtnClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosImagenes/ClienteIcon.png"))); // NOI18N
        BtnClientes.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Clientes");
        BtnClientes.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(BtnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        ProgramaAutos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ProgramaAutos.setForeground(new java.awt.Color(255, 255, 255));
        ProgramaAutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosImagenes/Logo150.png"))); // NOI18N
        Menu.add(ProgramaAutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 150, 100));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        Menu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 190, 20));

        BtnPlanilla.setBackground(new java.awt.Color(73, 176, 111));
        BtnPlanilla.setForeground(new java.awt.Color(255, 255, 255));
        BtnPlanilla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnPlanilla.setPreferredSize(new java.awt.Dimension(270, 51));
        BtnPlanilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnPlanillaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnPlanillaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnPlanillaMousePressed(evt);
            }
        });
        BtnPlanilla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosImagenes/payroll.png"))); // NOI18N
        BtnPlanilla.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Planilla de pago");
        BtnPlanilla.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(BtnPlanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, -1));

        BtnCatalogo.setBackground(new java.awt.Color(73, 176, 111));
        BtnCatalogo.setForeground(new java.awt.Color(255, 255, 255));
        BtnCatalogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnCatalogo.setPreferredSize(new java.awt.Dimension(270, 51));
        BtnCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCatalogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCatalogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCatalogoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnCatalogoMousePressed(evt);
            }
        });
        BtnCatalogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnCatalogo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Puestos");
        BtnCatalogo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 60, -1));

        Menu.add(BtnCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 130, 20));

        BtnSucursales.setBackground(new java.awt.Color(73, 176, 111));
        BtnSucursales.setForeground(new java.awt.Color(255, 255, 255));
        BtnSucursales.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnSucursales.setPreferredSize(new java.awt.Dimension(270, 51));
        BtnSucursales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSucursalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnSucursalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnSucursalesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnSucursalesMousePressed(evt);
            }
        });
        BtnSucursales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosImagenes/SucursalIcon.png"))); // NOI18N
        BtnSucursales.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Sucursales");
        BtnSucursales.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(BtnSucursales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, -1, -1));

        BtnUsuarios.setBackground(new java.awt.Color(73, 176, 111));
        BtnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        BtnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnUsuarios.setPreferredSize(new java.awt.Dimension(270, 51));
        BtnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnUsuariosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnUsuariosMousePressed(evt);
            }
        });
        BtnUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosImagenes/users.png"))); // NOI18N
        BtnUsuarios.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Usuarios");
        BtnUsuarios.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(BtnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, -1));

        BtnCerrarSesion.setBackground(new java.awt.Color(193, 82, 57));
        BtnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        BtnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnCerrarSesion.setPreferredSize(new java.awt.Dimension(270, 51));
        BtnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCerrarSesionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnCerrarSesionMousePressed(evt);
            }
        });
        BtnCerrarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosImagenes/LogOutIcon.png"))); // NOI18N
        BtnCerrarSesion.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Cerrar sesión");
        BtnCerrarSesion.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(BtnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, -1, -1));

        BtnTransacciones.setBackground(new java.awt.Color(73, 176, 111));
        BtnTransacciones.setForeground(new java.awt.Color(255, 255, 255));
        BtnTransacciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnTransacciones.setPreferredSize(new java.awt.Dimension(270, 51));
        BtnTransacciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnTransaccionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnTransaccionesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnTransaccionesMousePressed(evt);
            }
        });
        BtnTransacciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosImagenes/transaction.png"))); // NOI18N
        BtnTransacciones.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Transacciones ");
        BtnTransacciones.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(BtnTransacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, -1, -1));

        BtnCatalogo1.setBackground(new java.awt.Color(73, 176, 111));
        BtnCatalogo1.setForeground(new java.awt.Color(255, 255, 255));
        BtnCatalogo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnCatalogo1.setPreferredSize(new java.awt.Dimension(270, 51));
        BtnCatalogo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCatalogo1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCatalogo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCatalogo1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnCatalogo1MousePressed(evt);
            }
        });
        BtnCatalogo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnCatalogo1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Jornadas");
        BtnCatalogo1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 70, -1));

        Menu.add(BtnCatalogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 140, 20));

        BtnCatalogo2.setBackground(new java.awt.Color(73, 176, 111));
        BtnCatalogo2.setForeground(new java.awt.Color(255, 255, 255));
        BtnCatalogo2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnCatalogo2.setPreferredSize(new java.awt.Dimension(270, 51));
        BtnCatalogo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCatalogo2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCatalogo2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCatalogo2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnCatalogo2MousePressed(evt);
            }
        });
        BtnCatalogo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnCatalogo2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Ciudades");
        BtnCatalogo2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 70, -1));

        Menu.add(BtnCatalogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 140, 20));

        BtnCatalogo3.setBackground(new java.awt.Color(73, 176, 111));
        BtnCatalogo3.setForeground(new java.awt.Color(255, 255, 255));
        BtnCatalogo3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnCatalogo3.setPreferredSize(new java.awt.Dimension(270, 51));
        BtnCatalogo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCatalogo3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCatalogo3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCatalogo3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnCatalogo3MousePressed(evt);
            }
        });
        BtnCatalogo3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnCatalogo3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Marcas");
        BtnCatalogo3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 60, -1));

        Menu.add(BtnCatalogo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 130, 20));

        BtnEmpleados1.setBackground(new java.awt.Color(73, 176, 111));
        BtnEmpleados1.setForeground(new java.awt.Color(255, 255, 255));
        BtnEmpleados1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnEmpleados1.setPreferredSize(new java.awt.Dimension(270, 51));
        BtnEmpleados1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEmpleados1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEmpleados1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEmpleados1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnEmpleados1MousePressed(evt);
            }
        });
        BtnEmpleados1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnEmpleados1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Roles");
        BtnEmpleados1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 30));

        Menu.add(BtnEmpleados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 270, 30));

        Background.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 720));

        Title.setBackground(new java.awt.Color(255, 255, 255));
        Title.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TitleMouseDragged(evt);
            }
        });
        Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TitleMousePressed(evt);
            }
        });

        javax.swing.GroupLayout TitleLayout = new javax.swing.GroupLayout(Title);
        Title.setLayout(TitleLayout);
        TitleLayout.setHorizontalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        TitleLayout.setVerticalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        Background.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        Background.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 940, 690));

        red_squr.setBackground(new java.awt.Color(255, 255, 255));
        red_squr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        red_squr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                red_squrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                red_squrMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                red_squrMousePressed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout red_squrLayout = new javax.swing.GroupLayout(red_squr);
        red_squr.setLayout(red_squrLayout);
        red_squrLayout.setHorizontalGroup(
            red_squrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(red_squrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        red_squrLayout.setVerticalGroup(
            red_squrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(red_squrLayout.createSequentialGroup()
                .addComponent(exit)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        Background.add(red_squr, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 50, 30));

        Mnimizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Mnimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mnimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosImagenes/minimize-sign.png"))); // NOI18N
        Mnimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Mnimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MnimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MnimizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MnimizarMousePressed(evt);
            }
        });
        Background.add(Mnimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 36, -1));

        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPrincipalMouseEntered
      
    }//GEN-LAST:event_BtnPrincipalMouseEntered

    private void BtnPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPrincipalMouseExited
      
    }//GEN-LAST:event_BtnPrincipalMouseExited

    private void BtnPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPrincipalMousePressed
     
   
    }//GEN-LAST:event_BtnPrincipalMousePressed

    private void BtnVehiculosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVehiculosMouseEntered
   
    }//GEN-LAST:event_BtnVehiculosMouseEntered

    private void BtnVehiculosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVehiculosMouseExited
       
    }//GEN-LAST:event_BtnVehiculosMouseExited

    private void BtnVehiculosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVehiculosMousePressed

     
    }//GEN-LAST:event_BtnVehiculosMousePressed

    private void BtnVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVentasMouseEntered
     
    }//GEN-LAST:event_BtnVentasMouseEntered

    private void BtnVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVentasMouseExited
       
    }//GEN-LAST:event_BtnVentasMouseExited

    private void BtnVentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVentasMousePressed

    }//GEN-LAST:event_BtnVentasMousePressed

    private void BtnProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnProveedoresMouseEntered

    }//GEN-LAST:event_BtnProveedoresMouseEntered

    private void BtnProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnProveedoresMouseExited
 
    }//GEN-LAST:event_BtnProveedoresMouseExited

    private void BtnProveedoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnProveedoresMousePressed

    }//GEN-LAST:event_BtnProveedoresMousePressed

    private void BtnEmpleadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEmpleadosMouseEntered

    }//GEN-LAST:event_BtnEmpleadosMouseEntered

    private void BtnEmpleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEmpleadosMouseExited
    
    }//GEN-LAST:event_BtnEmpleadosMouseExited

    private void BtnEmpleadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEmpleadosMousePressed
    
    }//GEN-LAST:event_BtnEmpleadosMousePressed

    private void BtnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnClientesMouseEntered
  
    }//GEN-LAST:event_BtnClientesMouseEntered

    private void BtnClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnClientesMouseExited
  
    }//GEN-LAST:event_BtnClientesMouseExited

    private void BtnClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnClientesMousePressed
    
    }//GEN-LAST:event_BtnClientesMousePressed

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        red_squr.setBackground(new Color(204,0,0));
        exit.setForeground(Color.white);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        red_squr.setBackground(new Color(255,255,255));
        exit.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_exitMouseExited

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void red_squrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_squrMouseEntered
        red_squr.setBackground(new Color(204,0,0));
        exit.setForeground(Color.white);
    }//GEN-LAST:event_red_squrMouseEntered

    private void red_squrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_squrMouseExited
        red_squr.setBackground(new Color(255,255,255));
        exit.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_red_squrMouseExited

    private void red_squrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_squrMousePressed
        System.exit(0);
    }//GEN-LAST:event_red_squrMousePressed

   
    private void TitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleMouseDragged
      int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_TitleMouseDragged

    private void TitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_TitleMousePressed

    private void BtnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnClientesMouseClicked
     Clientes p2 = new Clientes ();
       ShowPanel((JPanel) p2.getContentPane());
    }//GEN-LAST:event_BtnClientesMouseClicked

    private void BtnPlanillaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPlanillaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPlanillaMouseEntered

    private void BtnPlanillaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPlanillaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPlanillaMouseExited

    private void BtnPlanillaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPlanillaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPlanillaMousePressed

    private void BtnCatalogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCatalogoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCatalogoMouseEntered

    private void BtnCatalogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCatalogoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCatalogoMouseExited

    private void BtnCatalogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCatalogoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCatalogoMousePressed

    private void BtnSucursalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSucursalesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSucursalesMouseEntered

    private void BtnSucursalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSucursalesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSucursalesMouseExited

    private void BtnSucursalesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSucursalesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSucursalesMousePressed

    private void BtnUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnUsuariosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUsuariosMouseEntered

    private void BtnUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnUsuariosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUsuariosMouseExited

    private void BtnUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnUsuariosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUsuariosMousePressed

    private void BtnPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPrincipalMouseClicked
 PrincipalMenu p1 = new PrincipalMenu () {};
       ShowPanel((JPanel) p1.getContentPane());     
    }//GEN-LAST:event_BtnPrincipalMouseClicked

    private void BtnCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarSesionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCerrarSesionMouseEntered

    private void BtnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarSesionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCerrarSesionMouseExited

    private void BtnCerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarSesionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCerrarSesionMousePressed

    private void MnimizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnimizarMousePressed
           this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MnimizarMousePressed

    private void MnimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnimizarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_MnimizarMouseExited

    private void MnimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnimizarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_MnimizarMouseEntered

    private void BtnSucursalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSucursalesMouseClicked
     Sucursales p3 = new Sucursales ();
       ShowPanel((JPanel) p3.getContentPane());
    }//GEN-LAST:event_BtnSucursalesMouseClicked

    private void BtnTransaccionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTransaccionesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTransaccionesMouseEntered

    private void BtnTransaccionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTransaccionesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTransaccionesMouseExited

    private void BtnTransaccionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTransaccionesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTransaccionesMousePressed

    private void BtnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarSesionMouseClicked
        this.dispose();
    Login loginForm = new Login(); 
    loginForm.setVisible(true); 
    }//GEN-LAST:event_BtnCerrarSesionMouseClicked

    private void BtnCatalogo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCatalogo1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCatalogo1MouseEntered

    private void BtnCatalogo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCatalogo1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCatalogo1MouseExited

    private void BtnCatalogo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCatalogo1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCatalogo1MousePressed

    private void BtnCatalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCatalogoMouseClicked
        Puestos p3 = new Puestos ();
        ShowPanel((JPanel) p3.getContentPane());
    }//GEN-LAST:event_BtnCatalogoMouseClicked

    private void BtnCatalogo2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCatalogo2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCatalogo2MouseEntered

    private void BtnCatalogo2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCatalogo2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCatalogo2MouseExited

    private void BtnCatalogo2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCatalogo2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCatalogo2MousePressed

    private void BtnCatalogo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCatalogo3MouseClicked
        Marcas p3 = new Marcas();
        ShowPanel((JPanel) p3.getContentPane());
    }//GEN-LAST:event_BtnCatalogo3MouseClicked

    private void BtnCatalogo3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCatalogo3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCatalogo3MouseEntered

    private void BtnCatalogo3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCatalogo3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCatalogo3MouseExited

    private void BtnCatalogo3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCatalogo3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCatalogo3MousePressed

    private void BtnEmpleados1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEmpleados1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEmpleados1MouseEntered

    private void BtnEmpleados1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEmpleados1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEmpleados1MouseExited

    private void BtnEmpleados1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEmpleados1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEmpleados1MousePressed

    private void BtnCatalogo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCatalogo1MouseClicked
        Jornadas p3 = new Jornadas ();
        ShowPanel((JPanel) p3.getContentPane());
    }//GEN-LAST:event_BtnCatalogo1MouseClicked

    private void BtnCatalogo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCatalogo2MouseClicked
        Ciudades p3 = new Ciudades ();
        ShowPanel((JPanel) p3.getContentPane());
    }//GEN-LAST:event_BtnCatalogo2MouseClicked

    private void BtnEmpleados1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEmpleados1MouseClicked
        Roles p3 = new Roles ();
        ShowPanel((JPanel) p3.getContentPane());
    }//GEN-LAST:event_BtnEmpleados1MouseClicked

    private void BtnVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVentasMouseClicked
        Factura p3 = new Factura();
        ShowPanel((JPanel) p3.getContentPane());
    }//GEN-LAST:event_BtnVentasMouseClicked

    
    private void ShowPanel(JPanel p) {
        p.setSize(940,550);
        p.setLocation(0,0);
        
        content.removeAll();
        content.add(p,BorderLayout.CENTER);
        content.revalidate(); 
        content.repaint(); 
    }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel BtnCatalogo;
    private javax.swing.JPanel BtnCatalogo1;
    private javax.swing.JPanel BtnCatalogo2;
    private javax.swing.JPanel BtnCatalogo3;
    private javax.swing.JPanel BtnCerrarSesion;
    private javax.swing.JPanel BtnClientes;
    private javax.swing.JPanel BtnEmpleados;
    private javax.swing.JPanel BtnEmpleados1;
    private javax.swing.JPanel BtnPlanilla;
    private javax.swing.JPanel BtnPrincipal;
    private javax.swing.JPanel BtnProveedores;
    private javax.swing.JPanel BtnSucursales;
    private javax.swing.JPanel BtnTransacciones;
    private javax.swing.JPanel BtnUsuarios;
    private javax.swing.JPanel BtnVehiculos;
    private javax.swing.JPanel BtnVentas;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel Mnimizar;
    private javax.swing.JLabel ProgramaAutos;
    private javax.swing.JPanel Title;
    public static javax.swing.JPanel content;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel red_squr;
    // End of variables declaration//GEN-END:variables
}
