/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectosuperautos;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement; 
import java.sql.ResultSet;
import java.sql.SQLException; 
import javax.swing.JOptionPane;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import Clases.Conexionsqlnetbeans;
import Clases.MantenimientoCatalogos;
import javax.swing.SwingUtilities;
/**
 *
 * @author Sthefany
 */
public class Puestos extends javax.swing.JFrame {
    Conexionsqlnetbeans cone        = new Conexionsqlnetbeans();
    DefaultTableModel   vrmodelo    = new DefaultTableModel();
    Statement           vrstmt      = null;
    ResultSet           vrrs        = null;
    String              vrtabla     = "PUESTOS";
    
    int fila;
    int codigo;
    
    /**
     * Creates new form Login
     */
    public Puestos() {
        initComponents(); 
        this.setLocationRelativeTo(null); 
        cone.obtenerconexion();
        mtd_mostrar_tabla();
        this.txtdescripcion.putClientProperty("id",0);
    }
    
    public boolean mtd_buscar(String vrsearch, boolean vrmodificando)
    {
        boolean found   = false;
        
        for (int row = 0; row < vrmodelo.getRowCount(); row++) {
            for (int col = 0; col < vrmodelo.getColumnCount(); col++) {
                Object cellValue = vrmodelo.getValueAt(row, col);
                
                if(vrsearch.equals(cellValue.toString()))
                {
                    this.tbl_detalle.setRowSelectionInterval(row, row);
                    this.tbl_detalle.setColumnSelectionInterval(col, col);

                    found = true;
                    System.out.println("0");
                    if(vrmodificando)
                    {
                        Integer vrid_encontrado;
                        MantenimientoCatalogos vrman = new MantenimientoCatalogos();
                        
                        vrid_encontrado = vrman.obtener_id(vrtabla, vrsearch);
                        
                        if(vrid_encontrado == codigo)
                        {
                            found = false;
                        }
                    }
                    System.out.println("1");
                    if (found) break;
                }
                else
                {
                    System.out.println("2");
                    found = false;
                }
            }
            System.out.println("3");
            if (found) break;
        }
        System.out.println("4");
        System.out.println(found);
        return found;
    }
    
    public void mtd_mostrar_tabla()
    {
        MantenimientoCatalogos vrman = new MantenimientoCatalogos();
        vrmodelo = vrman.obtener_catalogo_grid(vrtabla);        
        this.tbl_detalle.setModel(vrmodelo);
    }
    
    public void mtd_limpiar()
    {
        this.txtdescripcion.setText("");
        mtd_mostrar_tabla();
        codigo = 0;
        SwingUtilities.invokeLater(() -> txtdescripcion.requestFocusInWindow());
    }
    
//    private void mtd_cargar_catalogo()
//    {
//         MantenimientoCatalogos vrman = new MantenimientoCatalogos();
//         
//         
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnAgregar = new javax.swing.JButton();
        BtnAgregar1 = new javax.swing.JButton();
        BtnAgregar2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_detalle = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BtnAgregar.setBackground(new java.awt.Color(2, 167, 63));
        BtnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosImagenes/Diskete3 35x35.png"))); // NOI18N
        BtnAgregar.setText("Guardar");
        BtnAgregar.setBorderPainted(false);
        BtnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnAgregar.setIconTextGap(8);
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        BtnAgregar1.setBackground(new java.awt.Color(2, 167, 63));
        BtnAgregar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnAgregar1.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosImagenes/Clean 35x35.png"))); // NOI18N
        BtnAgregar1.setText("Limpiar");
        BtnAgregar1.setBorderPainted(false);
        BtnAgregar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnAgregar1.setIconTextGap(8);
        BtnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregar1ActionPerformed(evt);
            }
        });

        BtnAgregar2.setBackground(new java.awt.Color(193, 82, 57));
        BtnAgregar2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnAgregar2.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosImagenes/Bin 35x35.png"))); // NOI18N
        BtnAgregar2.setText("Eliminar");
        BtnAgregar2.setBorderPainted(false);
        BtnAgregar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnAgregar2.setIconTextGap(8);
        BtnAgregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregar2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Descripción:");

        txtdescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescripcionActionPerformed(evt);
            }
        });

        tbl_detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_detalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_detalleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_detalle);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrar Puestos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnAgregar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addContainerGap(279, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescripcionActionPerformed

    private void tbl_detalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_detalleMouseClicked
        fila                    = tbl_detalle.getSelectedRow();
        String vrdescripcion    = tbl_detalle.getValueAt(fila, 0).toString();
        this.txtdescripcion.setText(vrdescripcion);
        MantenimientoCatalogos vrman = new MantenimientoCatalogos();
        codigo = vrman.obtener_id(vrtabla, vrdescripcion);
    }//GEN-LAST:event_tbl_detalleMouseClicked

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Está seguro que la descripción escrita está correcta?");
        
        if (respuesta == 0)
        {
            String vrdescripcion = this.txtdescripcion.getText();
            boolean vrexiste ;

            if (codigo == 0)
            {
                vrexiste = mtd_buscar(vrdescripcion, false);

                if(vrexiste)
                {   
                    JOptionPane.showMessageDialog(this, "La descripción que escribió ya existe", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            else
            {
                vrexiste = mtd_buscar(vrdescripcion, true);

                if(vrexiste)
                {
                    JOptionPane.showMessageDialog(this, "La descripción que escribió ya existe", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

            if(!vrexiste)
            {
                if("".equals(vrdescripcion)) {
                    JOptionPane.showMessageDialog(this, "Por favor escriba una descripción", "Error", JOptionPane.ERROR_MESSAGE);
                } else {

                    MantenimientoCatalogos vrman = new MantenimientoCatalogos();
                    int vrresultado;

                    if (codigo == 0)
                    {
                        vrresultado = MantenimientoCatalogos.ingresar(vrdescripcion, "SP_" + vrtabla);
                    }
                    else
                    {
                        vrresultado = MantenimientoCatalogos.modificar(codigo, vrdescripcion, "SP_" + vrtabla);
                    }

                    JOptionPane.showMessageDialog(this, "El ítem ha sido guardado correctamente", "Error", JOptionPane.INFORMATION_MESSAGE);

                    mtd_limpiar();
                }
            }
        }
//        man.mantenimientoClientes(
//            0,
//            CboCiudades.getSelectedIndex(),
//            TxtNombre.getText(),
//            TxtID.getText(),
//            TxtTelefono.getText(),
//            TxtCorreo.getText(),
//            TxtDireccion.getText(),
//            "agregar"
//        );
//
//        JOptionPane.showMessageDialog(null, "Cliente registrado exitosamente");
//        limpiarCampos();
//
//        man.cargarTablaClientes(jdetalle, 0, 0, "", "", "", "", "", "mostrar");

    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregar1ActionPerformed
        mtd_limpiar();
    }//GEN-LAST:event_BtnAgregar1ActionPerformed

    private void BtnAgregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregar2ActionPerformed

        if(codigo == 0) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione un ítem de la lista", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea eliminar el ítem seleccionado?");
        
            if (respuesta == 0)
            {
                MantenimientoCatalogos vrman = new MantenimientoCatalogos();

                MantenimientoCatalogos.eliminar(codigo, "SP_" + vrtabla);

                JOptionPane.showMessageDialog(this, "El ítem ha sido eliminado correctamente", "Error", JOptionPane.INFORMATION_MESSAGE);

                mtd_limpiar();
            }
        }
    }//GEN-LAST:event_BtnAgregar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Puestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Puestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Puestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Puestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Puestos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnAgregar1;
    private javax.swing.JButton BtnAgregar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_detalle;
    private javax.swing.JTextField txtdescripcion;
    // End of variables declaration//GEN-END:variables
}
