/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectosuperautos;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import Clases.Conexionsqlnetbeans;
// Librerías para la conexión a la base de datos
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;

// Librerías para mostrar mensajes
import javax.swing.JOptionPane;

// Librerías para manejar componentes de la interfaz
import javax.swing.table.DefaultTableModel;  // Manejo de JTable (para mostrar datos en tablas)
import javax.swing.JComboBox;               // Manejo de JComboBox dinámico
import javax.swing.event.DocumentEvent;     // Para detectar cambios en JTextField
import javax.swing.event.DocumentListener;  // Escucha eventos en JTextField

// Librerías para manejar eventos
import java.awt.event.ActionEvent;          // Eventos de botones (ActionEvent)
import java.awt.event.ActionListener;       // Listener para los botones
import java.awt.event.KeyAdapter;           // Eventos de teclado
import java.awt.event.KeyEvent;             // Eventos de tecla presionada

// Librerías para manejo de excepciones generales (opcional)
import java.lang.Exception;




/**
 *
 * @author aleja
 */
public class Ventas extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
        llenarComboBoxVehiculos();
    }
    
    Conexionsqlnetbeans conexion = new Conexionsqlnetbeans();
    Connection con = conexion.obtenerconexion();

    private void llenarComboBoxVehiculos() {
    try (Connection conexion = Conexionsqlnetbeans.conectar()) {
        String sql = "SELECT ID, VIN FROM VEHICULOS";
        java.sql.Statement stmt = conexion.createStatement();
        java.sql.ResultSet rs = stmt.executeQuery(sql);

        cmbVehiculo.removeAllItems();
        while (rs.next()) {
            String item = rs.getInt("ID") + " - " + rs.getString("VIN");
            cmbVehiculo.addItem(item);
        }
    } catch (Exception e) {
        System.err.println("Error al llenar comboBox de vehículos: " + e.getMessage());
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCompra = new javax.swing.JButton();
        btnRenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtRTN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbVehiculo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRentaDiaria = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCantidadDias = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtValorVehiculo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnGuardarCompra = new javax.swing.JButton();
        btnGuardarRenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnCompra.setText("COMPRA");
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });

        btnRenta.setText("RENTA");
        btnRenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("RTN:");

        jLabel3.setText("Teléfono:");

        jLabel4.setText("Correo Electrónico:");

        jButton3.setText("Nuevo Cliente");

        jLabel5.setText("CLIENTE");

        jLabel6.setText("Vehículo");

        cmbVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("AÑO:");

        jLabel8.setText("MODELO:");

        jLabel9.setText("PLACA:");

        jLabel10.setText("Valor Renta Diaria:");

        txtRentaDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRentaDiariaActionPerformed(evt);
            }
        });

        jLabel11.setText("Cantidad Días");

        txtCantidadDias.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadDiasActionPerformed(evt);
            }
        });

        jLabel12.setText("Valor Vehículo:");

        jLabel13.setText("Total:");

        txtAno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtModelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPlaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("VENTAS SUPERAUTOS");

        btnGuardarCompra.setText("Guardar Compra");
        btnGuardarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCompraActionPerformed(evt);
            }
        });

        btnGuardarRenta.setText("Guardar Renta");
        btnGuardarRenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(btnCompra))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCorreo)
                                        .addComponent(txtTelefono)
                                        .addComponent(txtRTN)
                                        .addComponent(txtNombre)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtRentaDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValorVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addComponent(btnRenta)
                                .addGap(165, 165, 165))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cmbVehiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(67, 67, 67)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCantidadDias)
                                            .addComponent(jLabel11)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnGuardarCompra)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGuardarRenta)
                                        .addGap(28, 28, 28)))))))
                .addGap(81, 81, 81))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(342, 342, 342))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCompra)
                            .addComponent(btnRenta))
                        .addGap(52, 52, 52)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel6)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(cmbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtCantidadDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel9)))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtRentaDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtValorVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardarCompra)
                            .addComponent(btnGuardarRenta))))
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        // TODO add your handling code here:
        
    txtCantidadDias.setEnabled(false);
    txtRentaDiaria.setEnabled(false);
    txtValorTotal.setEnabled(true);
    txtValorTotal.setText(txtValorVehiculo.getText());
        
    }//GEN-LAST:event_btnCompraActionPerformed

    private void guardarRenta() {
    // Obtén los datos del cliente
    String nombreCliente = txtNombre.getText();
    String rtn = txtRTN.getText();
    String telefono = txtTelefono.getText();
    String correo = txtCorreo.getText();

    // Obtén los datos del vehículo
    String vehiculoSeleccionado = (String) cmbVehiculo.getSelectedItem();
    int idVehiculo = Integer.parseInt(vehiculoSeleccionado.split(" - ")[0]); // Extraer el ID del vehículo
    double rentaDiaria = Double.parseDouble(txtRentaDiaria.getText()); // Renta diaria del vehículo
    int cantidadDias = Integer.parseInt(txtCantidadDias.getText()); // Cantidad de días de renta

    // Calcular el total
    double total = rentaDiaria * cantidadDias;

    try (Connection conexion = new Conexionsqlnetbeans().obtenerconexion()) {
        // Paso 1: Guardar al cliente (puedes omitir si el cliente ya existe en la base de datos)
        String sqlCliente = "INSERT INTO CLIENTES (NOMBRE, RTN, TELEFONO, CORREO) VALUES (?, ?, ?, ?)";
        PreparedStatement pstCliente = conexion.prepareStatement(sqlCliente, Statement.RETURN_GENERATED_KEYS);
        pstCliente.setString(1, nombreCliente);
        pstCliente.setString(2, rtn);
        pstCliente.setString(3, telefono);
        pstCliente.setString(4, correo);
        pstCliente.executeUpdate();

        // Obtener el ID del cliente recién insertado
        ResultSet rsCliente = pstCliente.getGeneratedKeys();
        int idCliente = 0;
        if (rsCliente.next()) {
            idCliente = rsCliente.getInt(1);
        }

        // Paso 2: Guardar la factura (renta)
        String sqlFactura = "INSERT INTO FACTURAS (ID_CLIENTE, ID_TIPO, FECHA, NUMERO, TOTAL) VALUES (?, ?, GETDATE(), ?, ?)";
        PreparedStatement pstFactura = conexion.prepareStatement(sqlFactura, Statement.RETURN_GENERATED_KEYS);
        pstFactura.setInt(1, idCliente); // ID del cliente
        pstFactura.setInt(2, 2); // Tipo de factura: 2 = Renta
        pstFactura.setString(3, "RENTA-" + System.currentTimeMillis()); // Número único para la factura
        pstFactura.setDouble(4, total); // Total
        pstFactura.executeUpdate();

        // Obtener el ID de la factura recién insertada
        ResultSet rsFactura = pstFactura.getGeneratedKeys();
        int idFactura = 0;
        if (rsFactura.next()) {
            idFactura = rsFactura.getInt(1);
        }

        // Paso 3: Guardar el detalle de la factura
        String sqlDetalle = "INSERT INTO FACTURAS_DETALLE (ID_FACTURA, ID_VEHICULO, CANTIDAD, PRECIO_COSTO, PRECIO_VENTA, GARANTIA, ENTREGA_PROGRAMADA) VALUES (?, ?, ?, ?, ?, ?, DATEADD(DAY, ?, GETDATE()))";
        PreparedStatement pstDetalle = conexion.prepareStatement(sqlDetalle);
        pstDetalle.setInt(1, idFactura); // ID de la factura
        pstDetalle.setInt(2, idVehiculo); // ID del vehículo
        pstDetalle.setInt(3, 1); // Cantidad (siempre 1 para rentas de vehículos)
        pstDetalle.setDouble(4, 0.0); // Precio de costo (puedes ajustar según tu base de datos)
        pstDetalle.setDouble(5, total); // Precio de renta total
        pstDetalle.setInt(6, 0); // Garantía (ajusta si tienes un valor para esto)
        pstDetalle.setInt(7, cantidadDias); // Días para calcular la fecha de entrega
        pstDetalle.executeUpdate();

        // Confirmar éxito
        JOptionPane.showMessageDialog(this, "Renta registrada correctamente.");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al registrar la renta: " + e.getMessage());
    }
}


    
    
    private void btnRentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentaActionPerformed
        // TODO add your handling code here:
        
        // Habilitar campos necesarios para una renta
    txtCantidadDias.setEnabled(true);
    txtRentaDiaria.setEnabled(true);
    txtValorTotal.setEnabled(false);

    // Agregar listener para calcular automáticamente el total
    txtCantidadDias.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            calcularTotalRenta();
        }
    });

    txtRentaDiaria.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            calcularTotalRenta();
        }
    });
}

// Método para calcular el total en una renta
    private void calcularTotalRenta() {
    try {
        int dias = Integer.parseInt(txtCantidadDias.getText());
        double rentaDiaria = Double.parseDouble(txtRentaDiaria.getText());
        double total = dias * rentaDiaria;
        txtValorTotal.setText(String.valueOf(total));
    } catch (NumberFormatException e) {
        // Manejo de error por entrada inválida
        txtValorTotal.setText("0");
    }
    
        
    }//GEN-LAST:event_btnRentaActionPerformed
    
private void guardarCompra() {
    // Obtén los datos del cliente
    String nombreCliente = txtNombre.getText();
    String rtn = txtRTN.getText();
    String telefono = txtTelefono.getText();
    String correo = txtCorreo.getText();

    // Obtén los datos del vehículo
    String vehiculoSeleccionado = (String) cmbVehiculo.getSelectedItem();
    int idVehiculo = Integer.parseInt(vehiculoSeleccionado.split(" - ")[0]); // Extraer el ID del vehículo
    double valorVehiculo = Double.parseDouble(txtValorVehiculo.getText()); // Total del vehículo

    try (Connection conexion = new Conexionsqlnetbeans().obtenerconexion()) {
        // Paso 1: Guardar al cliente (puedes omitir si el cliente ya existe en la base de datos)
        String sqlCliente = "INSERT INTO CLIENTES (NOMBRE, RTN, TELEFONO, CORREO) VALUES (?, ?, ?, ?)";
        PreparedStatement pstCliente = conexion.prepareStatement(sqlCliente, Statement.RETURN_GENERATED_KEYS);
        pstCliente.setString(1, nombreCliente);
        pstCliente.setString(2, rtn);
        pstCliente.setString(3, telefono);
        pstCliente.setString(4, correo);
        pstCliente.executeUpdate();

        // Obtener el ID del cliente recién insertado
        ResultSet rsCliente = pstCliente.getGeneratedKeys();
        int idCliente = 0;
        if (rsCliente.next()) {
            idCliente = rsCliente.getInt(1);
        }

        // Paso 2: Guardar la factura (venta)
        String sqlFactura = "INSERT INTO FACTURAS (ID_CLIENTE, ID_TIPO, FECHA, NUMERO, TOTAL) VALUES (?, ?, GETDATE(), ?, ?)";
        PreparedStatement pstFactura = conexion.prepareStatement(sqlFactura, Statement.RETURN_GENERATED_KEYS);
        pstFactura.setInt(1, idCliente); // ID del cliente
        pstFactura.setInt(2, 1); // Tipo de factura: 1 = Venta
        pstFactura.setString(3, "VENTA-" + System.currentTimeMillis()); // Número único para la factura
        pstFactura.setDouble(4, valorVehiculo); // Total
        pstFactura.executeUpdate();

        // Obtener el ID de la factura recién insertada
        ResultSet rsFactura = pstFactura.getGeneratedKeys();
        int idFactura = 0;
        if (rsFactura.next()) {
            idFactura = rsFactura.getInt(1);
        }

        // Paso 3: Guardar el detalle de la factura
        String sqlDetalle = "INSERT INTO FACTURAS_DETALLE (ID_FACTURA, ID_VEHICULO, CANTIDAD, PRECIO_COSTO, PRECIO_VENTA) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement pstDetalle = conexion.prepareStatement(sqlDetalle);
        pstDetalle.setInt(1, idFactura); // ID de la factura
        pstDetalle.setInt(2, idVehiculo); // ID del vehículo
        pstDetalle.setInt(3, 1); // Cantidad (siempre 1 para ventas de vehículos)
        pstDetalle.setDouble(4, 0.0); // Precio de costo (puedes ajustar según tu base de datos)
        pstDetalle.setDouble(5, valorVehiculo); // Precio de venta
        pstDetalle.executeUpdate();

        // Confirmar éxito
        JOptionPane.showMessageDialog(this, "Compra registrada correctamente.");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al registrar la compra: " + e.getMessage());
    }
}



    private void btnGuardarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCompraActionPerformed
        // TODO add your handling code here:
        
    guardarCompra();


        
    }//GEN-LAST:event_btnGuardarCompraActionPerformed

    private void btnGuardarRentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRentaActionPerformed
        // TODO add your handling code here:
        
        
        guardarRenta();
    }//GEN-LAST:event_btnGuardarRentaActionPerformed

    private void txtCantidadDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadDiasActionPerformed
        // TODO add your handling code here:
        
        txtCantidadDias.addKeyListener(new java.awt.event.KeyAdapter() {
    public void keyReleased(java.awt.event.KeyEvent evt) {
        calcularTotalRenta();
    }
});
    }//GEN-LAST:event_txtCantidadDiasActionPerformed

    private void txtRentaDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRentaDiariaActionPerformed
        // TODO add your handling code here:}}
        txtRentaDiaria.addKeyListener(new java.awt.event.KeyAdapter() {
    public void keyReleased(java.awt.event.KeyEvent evt) {
        calcularTotalRenta();
    }
});
    }//GEN-LAST:event_txtRentaDiariaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnGuardarCompra;
    private javax.swing.JButton btnGuardarRenta;
    private javax.swing.JButton btnRenta;
    private javax.swing.JComboBox<String> cmbVehiculo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtCantidadDias;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtRTN;
    private javax.swing.JTextField txtRentaDiaria;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtValorTotal;
    private javax.swing.JTextField txtValorVehiculo;
    // End of variables declaration//GEN-END:variables
}
